### ISSUE TITLE
Family Tree V3 Support

### ISSUE THREAD

**Issue by SZanlongo** [eosrei/ftgc#1]
Hi, I'm in a similar situation where I need to modernize some old genealogical records.

Did you ever get a chance to add V3 support for F3M/F3D files?

**Comment by 13rac1** [comment]
Now here's a project I haven't heard in a long time!

> Did you ever get a chance to add V3 support for F3M/F3D files?

No, I didn't. It should be easy enough to fork this and modify it for v3 though http://justsolve.archiveteam.org/wiki/Softdisk_Family_Tree#Family_Tree_3 The structure is similar.

**Comment by SZanlongo** [comment]
Found out that Softdisk Family Tree (at least V3) allows for exporting to a GED format, which can then be imported into Gramps (and many other variants as well). Thanks!
